# Generated by Django 2.2 on 2019-04-05 01:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingreso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_factura', models.DateField()),
                ('importe', models.DecimalField(decimal_places=2, max_digits=2)),
                ('factura', models.CharField(max_length=10)),
                ('tipo_producto', models.CharField(max_length=45)),
                ('fecha_proxima', models.DateField()),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cliente_app.Cliente')),
            ],
        ),
    ]
