# Generated by Django 2.2 on 2019-04-05 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingreso_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingreso',
            name='fecha_proxima',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='ingreso',
            name='importe',
            field=models.CharField(max_length=10),
        ),
    ]
