# Generated by Django 2.2 on 2019-04-03 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente_app', '0002_cliente_vendedor'),
        ('ingreso_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingreso',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cliente_app.Cliente'),
        ),
    ]
