# Generated by Django 2.2 on 2019-04-05 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingreso_app', '0003_auto_20190404_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingreso',
            name='fecha_proxima',
            field=models.CharField(max_length=10),
        ),
    ]
