# Generated by Django 2.2 on 2019-04-03 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=70)),
                ('apellido', models.CharField(max_length=15)),
                ('correo', models.CharField(max_length=70)),
                ('fecha_incorporacion', models.DateField()),
                ('activo', models.BooleanField()),
                ('puesto', models.CharField(max_length=15)),
            ],
        ),
    ]
