# Generated by Django 2.2 on 2019-04-11 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='fecha',
            field=models.CharField(max_length=15),
        ),
    ]
